Experiment: BERT on full_dataset
------
For this experiment we assume that the dataset is stored in a pkl file.

In [1]:
import sys; sys.path.append('../..')
import torch
from bias_classification import prepare_model 
from src.utils import *

%load_ext autoreload
%autoreload 2

In [2]:
params = prepare_model.intialize_params("experiment_params.json")

In [3]:
import pickle
dataset = pickle.load(open('dataset.pkl', 'rb'))

In [4]:
# Run to print out the current key names in the dataset
dataset.get_key_names()

dict_keys(['pre_ids', 'masks', 'pre_lens', 'post_in_ids', 'post_out_ids', 'pre_tok_label_ids', 'post_tok_label_ids', 'rel_ids', 'pos_ids', 'categories', 'index', 'pos', 'pos_weak_labels', 'bias_label'])

In [5]:
tok2id = prepare_model.get_tok2id(params.intermediary_task)

06/07/2019 18:25:50 - INFO - pytorch_pretrained_bert.tokenization -   loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at ../../../tasks/bias_classification/results/cache/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084


In [6]:
print(tok2id['[CLS]'])

101


In [7]:
original_tokids = dataset.get_val("pre_ids")

In [8]:
rows, cols = original_tokids.shape

In [9]:
new_col = tok2id['[CLS]'] * torch.ones(rows,1, dtype=torch.long)

In [10]:
print(new_col.shape)
print(original_tokids.shape)

torch.Size([51444, 1])
torch.Size([51444, 80])


In [11]:
tok_ids = torch.cat((new_col,original_tokids), dim=1)[:,:80]

In [12]:
dataset.add_data(tok_ids, 'pre_ids')

In [13]:
mask = dataset.get_val("masks")

In [14]:
mask = -1 * (mask.to(torch.int8) - 1)

In [15]:
for row in range(len(dataset)):
    idx = mask[row].tolist().index(0)
    if idx == 80:
        continue
    mask[row,idx] = 1

In [16]:
mask = mask.to(torch.uint8)

In [17]:
dataset.add_data(mask, 'masks')

Run the cell below to reset params 
-----

In [18]:
#reloading classification experiment with new experiments
params = prepare_model.intialize_params("experiment_params.json") 
classification_experiment = prepare_model.initialize_classification_experiment(params.final_task)

06/07/2019 17:37:08 - INFO - pytorch_pretrained_bert.modeling -   loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /sailhome/rdm/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
06/07/2019 17:37:08 - INFO - pytorch_pretrained_bert.modeling -   extracting archive file /sailhome/rdm/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir /tmp/tmpzpcfgca7
06/07/2019 17:37:12 - INFO - pytorch_pretrained_bert.modeling -   Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 

In [19]:
print(params.final_task)

{'model': 'bert_basic_uncased_sequence', 'output_dim': 1, 'data_split': {'train_split': 0.001, 'eval_split': 0.001, 'test_split': 0}, 'training_params': {'optimizer': 'adam', 'loss': 'bce_with_logits', 'num_epochs': 2, 'batch_size': 64, 'lr': 0.001}}


Boostrapping procedure 

In [20]:
bert_args = {'attention_mask_key': 'masks', 'num_bootstrap_iters':20}
statistics = run_boostrapping(classification_experiment, dataset, params, input_key='pre_ids', label_key='bias_label', threshold=0.42, **bert_args)

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 1, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)
tensor([[  101, 21146, 18569,  ...,     0,     0,     0],
        [  101,  1996,  4035,  ...,     0,     0,     0],
        [  101, 10424, 20518,  ...,     0,     0,     0],
        ...,
        [  101,  2077,  3352,  ...,  1012,     0,     0],
        [  101,  2005,  2012,  ...,     0,     0,     0],
        [  101,  2648,  3834,  ...,     0,     0,     0]], device='cuda:0')
0.7010625600814819


tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 1, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)
tensor([[  101, 21146, 18569,  ...,     0,     0,     0],
        [  101,  1996,  4035,  ...,     0,     0,     0],
        [  101, 10424, 20518,  ...,     0,     0,     0],
        ...,
        [  101,  2077,  3352,  ...,  1012,     0,     0],
        [  101,  2005,  2012,  ...,     0,     0,     0],
        [  101,  2648,  3834,  ...,     0,     0,     0]], device='cuda:0')
1.6438924074172974


tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)
tensor([[ 101, 1996, 3278,  ...,    0,    0,    0],
        [ 101, 2002, 2001,  ...,    0,    0,    0],
        [ 101, 1996, 4598,  ...,    0,    0,    0],
        ...,
        [ 101, 2002, 2052,  ...,    0,    0,    0],
        [ 101, 2012, 1996,  ..., 5143, 5196, 1012],
        [ 101, 2065, 1996,  ...,    0,    0,    0]], device='cuda:0')
0.7005409598350525


tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)
tensor([[ 101, 1996, 3278,  ...,    0,    0,    0],
        [ 101, 2002, 2001,  ...,    0,    0,    0],
        [ 101, 1996, 4598,  ...,    0,    0,    0],
        ...,
        [ 101, 2002, 2052,  ...,    0,    0,    0],
        [ 101, 2012, 1996,  ..., 5143, 5196, 1012],
        [ 101, 2065, 1996,  ...,    0,    0,    0]], device='cuda:0')
0.7091359496116638


tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)
tensor([[  101,  1996,  2958,  ...,     0,     0,     0],
        [  101,  1037, 25908,  ...,     0,     0,     0],
        [  101,  2174,  1010,  ...,     0,     0,     0],
        ...,
        [  101,  2048,  5611,  ...,     0,     0,     0],
        [  101,  1999,  2337,  ...,     0,     0,     0],
        [  101,  2012,  5096,  ...,     0,     0,     0]], device='cuda:0')
0.6845828890800476


tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)
tensor([[  101,  1996,  2958,  ...,     0,     0,     0],
        [  101,  1037, 25908,  ...,     0,     0,     0],
        [  101,  2174,  1010,  ...,     0,     0,     0],
        ...,
        [  101,  2048,  5611,  ...,     0,     0,     0],
        [  101,  1999,  2337,  ...,     0,     0,     0],
        [  101,  2012,  5096,  ...,     0,     0,     0]], device='cuda:0')
1.2514487504959106


tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)
tensor([[  101,  1996,  3287,  ...,     0,     0,     0],
        [  101,  1996,  9935,  ...,     0,     0,     0],
        [  101,  2016, 18807,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  4668,  ...,     0,     0,     0],
        [  101,  4487,  7361,  ...,     0,     0,     0],
        [  101,  2130,  3282,  ...,     0,     0,     0]], device='cuda:0')
0.6644759178161621


tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)
tensor([[  101,  1996,  3287,  ...,     0,     0,     0],
        [  101,  1996,  9935,  ...,     0,     0,     0],
        [  101,  2016, 18807,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  4668,  ...,     0,     0,     0],
        [  101,  4487,  7361,  ...,     0,     0,     0],
        [  101,  2130,  3282,  ...,     0,     0,     0]], device='cuda:0')
0.9123970866203308


tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)
tensor([[  101, 12312,  2078,  ...,     0,     0,     0],
        [  101, 15764,  2609,  ...,     0,     0,     0],
        [  101, 28293,  1005,  ...,     0,     0,     0],
        ...,
        [  101,  2530,  5784,  ...,     0,     0,     0],
        [  101,  2023, 23273,  ...,     0,     0,     0],
        [  101,  2116,  2111,  ...,     0,     0,     0]], device='cuda:0')
0.6871629357337952


tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)
tensor([[  101, 12312,  2078,  ...,     0,     0,     0],
        [  101, 15764,  2609,  ...,     0,     0,     0],
        [  101, 28293,  1005,  ...,     0,     0,     0],
        ...,
        [  101,  2530,  5784,  ...,     0,     0,     0],
        [  101,  2023, 23273,  ...,     0,     0,     0],
        [  101,  2116,  2111,  ...,     0,     0,     0]], device='cuda:0')
0.8954633474349976


KeyboardInterrupt: 

In [ ]:
statistics

New run 

## No bootstrapping -- cannot calculate 95% confidence intervals 

In [18]:
params = prepare_model.intialize_params("experiment_params.json") 
classification_experiment = prepare_model.initialize_classification_experiment(params.final_task)

06/07/2019 18:25:58 - INFO - pytorch_pretrained_bert.modeling -   loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /sailhome/rdm/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
06/07/2019 18:25:58 - INFO - pytorch_pretrained_bert.modeling -   extracting archive file /sailhome/rdm/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir /tmp/tmphmd8w9ie
06/07/2019 18:26:02 - INFO - pytorch_pretrained_bert.modeling -   Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 

In [19]:
data_split = params.final_task['data_split']
batch_size = params.final_task['training_params']['batch_size']
train_dataloader, eval_dataloader, test_dataloader = dataset.split_train_eval_test(**data_split, batch_size=batch_size)

In [20]:
bert_args = {'attention_mask_key': 'masks', 'num_bootstrap_iters':20}
losses, evaluations = classification_experiment.train_model(train_dataloader, eval_dataloader, input_key='pre_ids', label_key='bias_label', threshold=0.42, **bert_args)

tensor([[0.1931],
        [0.3275],
        [0.4975],
        [0.5178],
        [0.3146]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5898348689079285


tensor([[1.7519],
        [1.2113],
        [1.8361],
        [1.3548],
        [1.0269]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.42622146010398865


tensor([[ 1.9493],
        [ 2.4012],
        [ 2.4119],
        [ 2.5295],
        [-0.9420]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.14231112599372864


tensor([[-0.3927],
        [ 0.5768],
        [-1.2920],
        [-0.2987],
        [-2.6147]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.7626725435256958


tensor([[5.4913],
        [5.7815],
        [5.4742],
        [5.4188],
        [5.3741]], device='cuda:0', grad_fn=<ThAddmmBackward>)
1.0788997411727905


tensor([[4.0821],
        [4.1538],
        [4.1481],
        [4.3774],
        [4.2943]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.8736573457717896


tensor([[3.0265],
        [3.0069],
        [3.0816],
        [2.9741],
        [2.4886]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5517371296882629


tensor([[1.2057],
        [1.3587],
        [1.8154],
        [1.3494],
        [1.4238]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5023323893547058


tensor([[0.6344],
        [0.3902],
        [0.4479],
        [0.0776],
        [0.8424]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.6584174633026123


tensor([[0.4727],
        [0.5778],
        [0.4597],
        [0.5631],
        [0.3656]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.552523136138916


tensor([[0.7922],
        [0.9202],
        [0.6266],
        [0.6281],
        [0.7255]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5369936227798462


tensor([[1.3096],
        [1.4866],
        [1.5567],
        [1.3242],
        [1.4251]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.502128541469574


tensor([[1.4387],
        [1.4405],
        [1.6989],
        [1.7547],
        [1.4466]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48218002915382385


tensor([[1.2328],
        [1.6770],
        [1.8029],
        [1.4602],
        [1.5796]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5110864639282227


tensor([[1.5282],
        [1.2672],
        [1.2828],
        [1.3688],
        [1.2540]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48417362570762634


tensor([[1.3083],
        [1.4055],
        [0.9977],
        [1.3051],
        [1.3691]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5216150879859924


tensor([[1.5263],
        [1.2155],
        [1.2482],
        [1.4316],
        [1.2470]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48451024293899536


tensor([[1.1086],
        [1.2036],
        [1.3979],
        [1.3324],
        [1.2356]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4986850917339325


tensor([[1.4762],
        [1.4924],
        [1.4978],
        [1.5133],
        [1.6395]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5252594947814941


tensor([[1.4695],
        [1.3806],
        [1.4465],
        [1.4619],
        [1.2397]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4690239131450653


tensor([[1.6505],
        [1.7237],
        [1.8971],
        [1.6901],
        [1.5789]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48304376006126404


tensor([[1.8158],
        [1.7673],
        [2.0203],
        [1.8922],
        [1.6696]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4830976128578186


tensor([[1.6305],
        [1.6732],
        [1.3967],
        [1.1151],
        [1.3511]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4873635470867157


tensor([[0.8530],
        [1.2138],
        [1.2473],
        [1.2737],
        [1.3819]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5440421104431152


tensor([[1.0320],
        [1.0650],
        [1.2260],
        [1.2333],
        [0.7791]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4541330337524414


tensor([[1.5383],
        [1.0529],
        [1.1284],
        [1.0508],
        [1.2797]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5198231935501099


tensor([[1.4728],
        [1.1305],
        [1.3982],
        [0.8839],
        [1.3068]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5198356509208679


tensor([[1.4107],
        [1.4612],
        [1.5553],
        [1.4328],
        [1.7015]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.540306568145752


tensor([[1.6879],
        [1.3283],
        [1.3259],
        [1.4361],
        [1.2516]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47134706377983093


tensor([[1.2750],
        [1.4108],
        [1.7880],
        [1.3457],
        [1.4048]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49501797556877136


tensor([[1.6071],
        [1.9200],
        [1.1907],
        [1.5191],
        [1.4933]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49577292799949646


tensor([[1.5797],
        [1.6042],
        [1.4044],
        [1.1997],
        [1.5902]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.525840163230896


tensor([[1.4466],
        [1.4427],
        [1.8031],
        [1.3327],
        [1.3189]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47319671511650085


tensor([[1.5135],
        [1.1219],
        [1.1927],
        [1.2450],
        [1.3252]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5119490623474121


tensor([[1.2960],
        [0.8926],
        [0.7454],
        [0.9207],
        [1.0853]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5370113253593445


tensor([[1.7027],
        [1.5163],
        [1.0749],
        [1.4863],
        [1.3994]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4966733455657959


tensor([[2.2705],
        [2.8338],
        [2.6890],
        [2.2811],
        [3.4718]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.7641530632972717


tensor([[1.3738],
        [1.3141],
        [1.3051],
        [1.3602],
        [1.2949]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.493802934885025


tensor([[0.9764],
        [1.1950],
        [0.8809],
        [1.0078],
        [1.2409]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5473653674125671


tensor([[1.2973],
        [1.0015],
        [1.5236],
        [1.0983],
        [1.2699]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5113577246665955


tensor([[1.0848],
        [1.5440],
        [0.9567],
        [1.2427],
        [1.4225]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5403563380241394


tensor([[1.3127],
        [1.1734],
        [1.2872],
        [1.0621],
        [1.4661]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5444544553756714


tensor([[1.3150],
        [1.9866],
        [1.1477],
        [1.4223],
        [1.4731]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5074950456619263


tensor([[1.1067],
        [1.5779],
        [1.6133],
        [1.2368],
        [1.3827]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5032831430435181


tensor([[1.3285],
        [1.5995],
        [1.6793],
        [1.3460],
        [1.2777]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4689699113368988


tensor([[1.3055],
        [1.2661],
        [1.3518],
        [1.3661],
        [1.4615]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5231203436851501


tensor([[1.5059],
        [1.0414],
        [1.0567],
        [1.4329],
        [1.4570]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5362693071365356


tensor([[1.2923],
        [1.0783],
        [1.3034],
        [1.0089],
        [1.4182]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5443249940872192


tensor([[1.5232],
        [1.4346],
        [1.3643],
        [1.2890],
        [1.0821]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4511573016643524


tensor([[1.6368],
        [1.3806],
        [1.6279],
        [1.5733],
        [1.4922]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49296480417251587


tensor([[1.4910],
        [2.0146],
        [1.5230],
        [1.6424],
        [1.5543]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4896943271160126


tensor([[1.9863],
        [1.5514],
        [1.9764],
        [1.9352],
        [1.5330]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.46278056502342224


tensor([[1.2090],
        [1.6878],
        [1.4365],
        [1.4252],
        [1.5427]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.519220769405365


tensor([[1.5894],
        [1.4091],
        [1.3064],
        [1.1339],
        [1.3363]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49850836396217346


tensor([[1.0459],
        [1.0171],
        [1.0240],
        [1.3772],
        [0.8115]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4641363322734833


tensor([[1.3569],
        [1.3926],
        [1.4368],
        [0.7755],
        [0.9799]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4683260917663574


tensor([[1.3579],
        [1.2881],
        [1.6661],
        [1.3959],
        [1.6415]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5370588302612305


tensor([[1.6101],
        [1.2419],
        [1.7197],
        [1.6019],
        [1.2798]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4618931710720062


tensor([[1.0925],
        [1.4113],
        [1.5327],
        [1.3805],
        [1.3226]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49720069766044617


tensor([[1.3081],
        [1.4898],
        [1.7844],
        [1.4359],
        [1.2211]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4581526815891266


tensor([[1.2631],
        [1.3798],
        [1.2416],
        [1.1219],
        [0.9337]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4548855721950531


tensor([[0.8562],
        [1.4772],
        [1.0148],
        [1.2534],
        [1.3915]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5467445254325867


tensor([[1.4145],
        [1.4434],
        [1.7515],
        [1.6586],
        [1.6499]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5178915858268738


tensor([[1.5385],
        [1.9856],
        [1.9576],
        [2.2246],
        [1.8022]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5025508999824524


tensor([[1.9172],
        [1.5538],
        [1.7710],
        [1.8233],
        [1.8718]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5301366448402405


tensor([[1.8844],
        [1.6581],
        [1.2201],
        [1.5609],
        [1.6650]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5206670165061951


tensor([[1.4854],
        [1.4548],
        [1.3785],
        [1.5513],
        [1.1260]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.44756269454956055


tensor([[0.4336],
        [0.5732],
        [1.1020],
        [1.1256],
        [0.9503]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5583392977714539


tensor([[1.6254],
        [1.3631],
        [1.3066],
        [1.2243],
        [1.5036]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5218343734741211


tensor([[1.3983],
        [1.0070],
        [1.8793],
        [1.3547],
        [1.2519]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48143091797828674


tensor([[1.5382],
        [1.1771],
        [1.6035],
        [1.3538],
        [1.2622]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47752833366394043


tensor([[1.3087],
        [1.2558],
        [1.4786],
        [1.7060],
        [1.6403]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5359066724777222


tensor([[1.7067],
        [1.6290],
        [1.6971],
        [1.2969],
        [1.5521]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49998560547828674


tensor([[1.2279],
        [1.3773],
        [1.5773],
        [1.3740],
        [1.6310]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5409913063049316


tensor([[1.2713],
        [1.2679],
        [1.5324],
        [1.5975],
        [1.5262]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5195900201797485


tensor([[1.3985],
        [1.4263],
        [1.3672],
        [1.4573],
        [1.0701]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4474683701992035


tensor([[1.1195],
        [1.3615],
        [1.4984],
        [1.0719],
        [0.9981]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.46373048424720764


tensor([[1.3841],
        [1.4354],
        [1.5581],
        [1.9082],
        [1.4319]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48251819610595703


tensor([[1.3718],
        [1.6040],
        [1.2650],
        [1.1515],
        [1.3671]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5053467750549316


tensor([[1.3213],
        [1.4581],
        [1.3201],
        [1.1742],
        [1.5714]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5423757433891296


tensor([[1.2191],
        [1.6969],
        [1.6661],
        [1.5426],
        [1.4568]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4920502305030823


tensor([[1.6543],
        [1.3863],
        [1.4184],
        [1.7304],
        [1.3638]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4739217460155487


tensor([[1.6790],
        [1.5470],
        [1.3913],
        [1.3072],
        [1.8281]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5605728030204773


tensor([[1.5967],
        [1.4192],
        [1.5766],
        [1.5894],
        [1.4101]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4806327521800995


tensor([[1.4234],
        [1.0918],
        [1.5497],
        [1.4845],
        [1.2602]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48236918449401855


tensor([[0.5249],
        [0.9970],
        [1.1911],
        [1.2209],
        [1.0991]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.537871778011322


tensor([[1.1424],
        [0.9119],
        [1.1239],
        [1.0440],
        [0.9652]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4971165657043457


tensor([[1.7789],
        [1.7283],
        [1.9791],
        [1.9455],
        [1.7681]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5016409754753113


tensor([[1.9527],
        [1.5302],
        [1.6456],
        [1.4521],
        [1.9878]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5663054585456848


tensor([[1.2867],
        [1.3299],
        [1.3693],
        [1.1382],
        [0.8789]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.44184866547584534


tensor([[1.1467],
        [0.8127],
        [1.2172],
        [0.9862],
        [1.1129]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5232772827148438


tensor([[1.2029],
        [1.2286],
        [1.6116],
        [1.3677],
        [1.1115]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.46483421325683594


tensor([[1.1915],
        [1.9021],
        [1.4132],
        [1.6794],
        [1.1625]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.44555899500846863


tensor([[1.3378],
        [1.3981],
        [1.2664],
        [1.8188],
        [1.5035]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5113440752029419


tensor([[1.7390],
        [1.6790],
        [1.8572],
        [1.6421],
        [1.7707]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5165666341781616


tensor([[0.9969],
        [1.2418],
        [1.3900],
        [1.3239],
        [1.2424]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5044512152671814


tensor([[1.2031],
        [1.1444],
        [1.2201],
        [1.5037],
        [1.6301]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.561485230922699


tensor([[1.0183],
        [1.2057],
        [1.2516],
        [1.3863],
        [1.2010]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5018283128738403


tensor([[1.1201],
        [1.1378],
        [1.1152],
        [1.2863],
        [1.1761]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5065609812736511


tensor([[1.1933],
        [1.6087],
        [1.1283],
        [1.4180],
        [1.4919]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5278643369674683


tensor([[1.2893],
        [1.5815],
        [1.4718],
        [1.5657],
        [1.6555]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5314030647277832


tensor([[1.5771],
        [1.6293],
        [1.3488],
        [1.3131],
        [1.5441]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5146788954734802


tensor([[1.6005],
        [1.5674],
        [1.6131],
        [1.3863],
        [1.6367]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.518532931804657


tensor([[1.7943],
        [1.4524],
        [1.3428],
        [1.5766],
        [1.4757]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4931013584136963


tensor([[1.2647],
        [1.6085],
        [1.2153],
        [1.4098],
        [1.4848]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5196728110313416


tensor([[1.2999],
        [1.0142],
        [1.4385],
        [1.3294],
        [1.4817]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.536939263343811


tensor([[1.1962],
        [1.2365],
        [1.4822],
        [1.5548],
        [1.2339]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48097649216651917


tensor([[1.7040],
        [1.5599],
        [1.0778],
        [1.1354],
        [1.4816]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5231720209121704


tensor([[1.2666],
        [1.7079],
        [1.3430],
        [1.3211],
        [1.2817]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4819960594177246


tensor([[1.7322],
        [1.1588],
        [1.1514],
        [1.5852],
        [1.0832]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.454351007938385


tensor([[1.3286],
        [1.2839],
        [1.4818],
        [1.3610],
        [1.1957]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47447314858436584


tensor([[1.0942],
        [1.1853],
        [1.2103],
        [1.4072],
        [1.4715]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5427085757255554


tensor([[1.8582],
        [1.2696],
        [1.3575],
        [1.3282],
        [1.4163]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4980010986328125


tensor([[1.1333],
        [1.4074],
        [1.4497],
        [1.6973],
        [1.4935]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5146303772926331


tensor([[1.4054],
        [1.5108],
        [1.8358],
        [1.4219],
        [1.6809]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5269127488136292


tensor([[1.2738],
        [1.8101],
        [1.0270],
        [1.2650],
        [1.4350]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.520291268825531


tensor([[1.3931],
        [1.3493],
        [1.3108],
        [1.2585],
        [1.3771]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5086567997932434


tensor([[1.1012],
        [1.3256],
        [1.4007],
        [1.3441],
        [1.5731]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5472339987754822


tensor([[1.2291],
        [1.1160],
        [1.2390],
        [1.1527],
        [1.2017]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.506687343120575


tensor([[1.2826],
        [1.2849],
        [1.2368],
        [0.9737],
        [1.1747]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.501650333404541


tensor([[1.3633],
        [1.4391],
        [1.4059],
        [1.3952],
        [1.4497]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5083436369895935


tensor([[1.6348],
        [1.2149],
        [1.6416],
        [1.6277],
        [1.4351]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4886074960231781


tensor([[1.4715],
        [1.6332],
        [1.2823],
        [1.4151],
        [1.7112]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5449272990226746


tensor([[1.5441],
        [1.5738],
        [1.3532],
        [1.4047],
        [1.4337]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.495744526386261


tensor([[1.0813],
        [1.5845],
        [1.3578],
        [1.2024],
        [1.3491]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5099945068359375


tensor([[1.4647],
        [1.1362],
        [1.4108],
        [1.3831],
        [1.0329]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.45317649841308594


tensor([[1.2401],
        [1.0813],
        [1.0619],
        [1.4266],
        [1.5478]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5597996711730957


tensor([[1.1515],
        [1.3631],
        [1.1192],
        [1.1421],
        [1.4679]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.547463595867157


tensor([[1.7304],
        [1.3774],
        [1.4553],
        [1.3981],
        [1.4642]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49815765023231506


tensor([[1.5895],
        [1.5813],
        [1.5662],
        [1.6799],
        [1.5547]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49593326449394226


tensor([[1.1217],
        [1.2752],
        [1.2993],
        [1.7114],
        [1.3432]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5021263957023621


tensor([[1.5847],
        [1.2741],
        [1.1181],
        [1.0551],
        [1.4457]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5343934893608093


tensor([[1.4208],
        [1.6885],
        [1.0767],
        [1.5175],
        [1.4578]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5088819861412048


tensor([[1.0381],
        [1.4320],
        [1.3714],
        [0.8633],
        [1.2900]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5257089138031006


tensor([[1.0530],
        [1.1242],
        [1.2106],
        [1.1743],
        [1.3604]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5399120450019836


tensor([[1.6833],
        [1.5736],
        [1.3735],
        [1.5883],
        [1.5795]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5074474215507507


tensor([[1.3991],
        [1.5798],
        [1.7423],
        [1.6417],
        [1.6550]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.515230119228363


tensor([[1.3678],
        [1.1619],
        [1.5812],
        [1.6026],
        [1.9577]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.591880738735199


tensor([[1.5230],
        [1.8888],
        [1.2719],
        [1.6596],
        [1.6105]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5103906989097595


tensor([[1.5346],
        [1.6620],
        [1.4309],
        [1.4276],
        [1.1680]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4474160671234131


tensor([[1.2980],
        [1.5563],
        [0.9347],
        [1.3029],
        [1.0949]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47759658098220825


tensor([[1.4391],
        [1.3318],
        [1.3319],
        [1.4423],
        [1.4610]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.512637734413147


tensor([[1.1565],
        [1.1027],
        [1.2943],
        [1.2185],
        [1.1006]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4898463189601898


tensor([[1.0888],
        [1.2748],
        [1.1989],
        [1.1374],
        [1.3609]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5334824919700623


tensor([[1.5989],
        [1.3772],
        [1.1682],
        [1.3902],
        [1.3297]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4933202862739563


tensor([[1.3212],
        [1.3872],
        [1.7632],
        [1.5517],
        [1.4732]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49790000915527344


tensor([[1.6657],
        [1.2936],
        [1.5580],
        [1.8475],
        [1.9035]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5590927004814148


tensor([[1.2113],
        [1.6886],
        [1.2939],
        [1.4588],
        [1.3202]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48769932985305786


tensor([[1.8047],
        [1.3022],
        [1.5453],
        [1.7804],
        [1.5996]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.505102276802063


tensor([[1.5588],
        [1.4923],
        [1.6450],
        [1.7022],
        [1.3329]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4609244763851166


tensor([[1.4153],
        [1.4452],
        [1.3722],
        [1.2585],
        [1.2683]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4842532277107239


tensor([[1.4531],
        [1.2956],
        [1.3459],
        [1.6379],
        [1.2949]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47961732745170593


tensor([[1.3048],
        [1.7314],
        [1.3655],
        [1.5990],
        [1.5417]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5100045800209045


tensor([[0.9522],
        [1.3600],
        [0.7885],
        [1.4854],
        [1.3230]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5385405421257019


tensor([[0.9054],
        [1.1130],
        [0.9348],
        [1.3073],
        [0.7911]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47187504172325134


tensor([[1.7540],
        [1.2708],
        [1.6193],
        [1.1831],
        [1.5232]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5150566697120667


tensor([[1.2508],
        [1.3376],
        [1.3693],
        [1.3832],
        [1.2472]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48697629570961


tensor([[1.1317],
        [1.3569],
        [1.2428],
        [1.5987],
        [1.3393]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5036471486091614


tensor([[1.1625],
        [1.5310],
        [1.2240],
        [1.5000],
        [1.3114]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4954274296760559


tensor([[1.3142],
        [1.2147],
        [1.3414],
        [0.9280],
        [1.3538]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5293685793876648


tensor([[1.7884],
        [1.6231],
        [1.2992],
        [1.6880],
        [1.5511]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4977830946445465


tensor([[1.8675],
        [1.7299],
        [1.9023],
        [1.5090],
        [1.2501]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.42954736948013306


tensor([[1.6619],
        [1.6263],
        [1.4479],
        [1.7688],
        [1.8031]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5355073809623718


tensor([[1.6403],
        [1.7993],
        [1.2880],
        [1.4561],
        [1.5471]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5047165155410767


tensor([[1.4530],
        [1.6002],
        [1.5284],
        [1.1124],
        [1.7282]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5532529950141907


tensor([[1.2813],
        [1.4410],
        [1.3738],
        [1.1578],
        [1.1228]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4721624553203583


tensor([[1.1124],
        [0.9940],
        [1.0075],
        [1.2051],
        [1.1214]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5151879191398621


tensor([[1.1515],
        [1.5343],
        [1.0542],
        [0.9177],
        [1.1245]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5021601319313049


tensor([[0.9621],
        [1.2059],
        [1.1996],
        [1.0948],
        [1.1867]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5181208848953247


tensor([[1.0026],
        [1.2724],
        [1.4915],
        [1.2082],
        [1.3008]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5131126046180725


tensor([[1.3932],
        [1.4266],
        [1.4529],
        [1.2402],
        [1.3299]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49316006898880005


tensor([[1.5507],
        [1.3890],
        [1.7797],
        [1.7146],
        [1.8366]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5441662669181824


tensor([[1.9231],
        [1.7353],
        [1.3694],
        [1.7384],
        [1.8292]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5330816507339478


tensor([[1.5574],
        [1.7766],
        [1.8566],
        [1.6572],
        [1.9930]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5575894713401794


tensor([[1.4659],
        [1.4746],
        [1.8682],
        [1.3431],
        [1.9097]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5674379467964172


tensor([[1.3152],
        [1.6049],
        [1.5301],
        [1.5416],
        [1.3938]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4852505624294281


tensor([[1.3094],
        [1.4981],
        [1.4866],
        [1.6824],
        [1.2744]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4672257900238037


tensor([[1.2803],
        [1.2926],
        [1.1927],
        [1.2923],
        [1.3779]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5196483731269836


tensor([[1.3281],
        [1.1399],
        [1.2330],
        [1.0904],
        [1.3487]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5275116562843323


tensor([[1.2840],
        [0.9960],
        [0.9253],
        [1.2992],
        [1.0990]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5041012167930603


tensor([[1.1479],
        [0.9622],
        [1.0855],
        [1.1039],
        [0.9709]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49370867013931274


tensor([[1.3619],
        [1.5170],
        [1.2339],
        [1.6743],
        [1.0106]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.434948593378067


tensor([[1.3268],
        [1.5202],
        [1.3705],
        [1.2574],
        [1.5704]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5338134169578552


tensor([[1.4145],
        [1.5494],
        [1.6211],
        [1.7119],
        [1.4935]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49052008986473083


tensor([[1.1598],
        [1.5082],
        [1.7594],
        [1.6188],
        [1.4342]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4920370280742645


tensor([[1.5595],
        [1.5904],
        [1.9627],
        [1.4322],
        [1.5314]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4898126721382141


tensor([[1.4352],
        [1.8391],
        [1.3205],
        [1.1407],
        [1.4051]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.499904066324234


tensor([[1.8328],
        [1.4826],
        [1.4449],
        [1.2973],
        [1.5811]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5148903727531433


tensor([[1.2110],
        [1.3733],
        [1.5139],
        [1.1732],
        [1.5862]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5454713106155396


tensor([[1.4502],
        [1.0950],
        [1.6392],
        [1.3996],
        [1.4201]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.506759524345398


tensor([[1.2136],
        [1.4939],
        [1.4737],
        [1.5590],
        [1.2675]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4750867486000061


tensor([[1.3342],
        [1.6235],
        [1.3742],
        [1.0884],
        [1.1053]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4641883969306946


tensor([[1.3156],
        [1.0834],
        [1.1401],
        [1.3464],
        [1.2516]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5082168579101562


tensor([[1.0726],
        [1.3315],
        [1.1342],
        [1.3798],
        [1.0648]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4785947799682617


tensor([[1.0432],
        [1.3368],
        [1.6066],
        [1.3122],
        [1.6760]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5607584714889526


tensor([[1.4881],
        [1.2406],
        [1.7656],
        [1.4228],
        [1.1324]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4486468434333801


tensor([[1.3215],
        [1.8007],
        [1.1498],
        [1.2696],
        [1.3682]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5014129281044006


tensor([[1.2651],
        [1.5950],
        [1.5208],
        [1.8611],
        [1.4652]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4897059500217438


tensor([[1.5180],
        [1.4819],
        [1.5342],
        [1.4878],
        [1.2427]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4596211910247803


tensor([[1.3758],
        [1.2725],
        [1.3141],
        [1.5597],
        [1.5864]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5347277522087097


tensor([[1.4915],
        [1.5150],
        [1.5481],
        [1.4755],
        [1.5187]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5034255385398865


tensor([[1.2600],
        [1.4859],
        [1.7035],
        [1.5041],
        [1.1671]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4519483745098114


tensor([[1.2789],
        [1.3808],
        [1.2656],
        [1.4947],
        [1.7331]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5632936358451843


tensor([[1.4173],
        [1.4731],
        [1.3841],
        [1.2644],
        [1.4619]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5132104754447937


tensor([[1.3701],
        [1.1610],
        [1.4565],
        [0.8933],
        [1.3281]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5229177474975586


tensor([[1.4454],
        [1.2399],
        [1.2863],
        [1.4247],
        [1.5530]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5340547561645508


tensor([[1.0248],
        [0.8596],
        [1.0975],
        [1.3668],
        [1.2275]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.53184574842453


tensor([[0.9897],
        [1.0821],
        [1.2106],
        [1.3978],
        [1.3021]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5264509916305542


tensor([[1.5355],
        [1.3605],
        [1.8458],
        [1.5053],
        [1.6495]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5191330313682556


tensor([[1.4371],
        [1.5220],
        [1.5783],
        [1.5362],
        [1.1789]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4480440318584442


tensor([[1.0917],
        [1.1099],
        [1.3550],
        [1.6650],
        [1.3405]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5100021362304688


tensor([[1.6054],
        [1.5341],
        [1.6941],
        [1.4049],
        [1.7053]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5277435183525085


tensor([[1.6419],
        [1.3959],
        [1.5403],
        [1.4364],
        [1.9630]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5800182223320007


tensor([[1.1947],
        [1.4821],
        [1.3555],
        [1.2215],
        [1.5368]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5376994609832764


tensor([[1.8457],
        [1.4518],
        [1.6184],
        [1.1774],
        [1.3683]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48029303550720215


tensor([[1.7859],
        [1.3571],
        [1.5221],
        [1.4599],
        [1.7313]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5369165539741516


tensor([[1.3844],
        [1.7529],
        [1.6280],
        [1.5147],
        [1.2185]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4477771818637848


tensor([[1.2091],
        [0.8999],
        [1.4663],
        [1.4341],
        [1.1099]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48370668292045593


tensor([[1.5693],
        [1.0949],
        [1.6183],
        [1.1444],
        [1.2059]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48055917024612427


tensor([[1.3429],
        [1.2395],
        [1.2434],
        [1.4269],
        [1.4292]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5197445154190063


tensor([[1.4376],
        [1.4962],
        [1.2010],
        [1.1436],
        [1.3620]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5089928507804871


tensor([[1.4570],
        [1.3184],
        [1.3054],
        [1.3401],
        [1.4488]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5157269835472107


tensor([[1.1263],
        [1.5106],
        [1.4101],
        [1.5792],
        [1.2702]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4807601571083069


tensor([[1.6057],
        [1.2356],
        [1.1536],
        [1.2715],
        [1.2178]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4872918128967285


tensor([[1.1784],
        [1.3330],
        [1.1772],
        [1.2515],
        [1.2091]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49856558442115784


tensor([[1.2469],
        [1.3330],
        [1.2323],
        [1.1947],
        [1.6821]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.571946918964386


tensor([[1.4486],
        [1.6784],
        [1.5476],
        [1.3081],
        [1.2544]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.46393823623657227


tensor([[1.4046],
        [1.6800],
        [1.4555],
        [1.6343],
        [1.3307]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4687116742134094


tensor([[1.7121],
        [1.5531],
        [1.8445],
        [1.4938],
        [1.4107]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4672488272190094


tensor([[1.7380],
        [1.4676],
        [1.7249],
        [1.2540],
        [1.4506]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4891311228275299


tensor([[1.1643],
        [1.3721],
        [1.6228],
        [1.2327],
        [1.0969]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4637211263179779


tensor([[1.7937],
        [1.1354],
        [1.1438],
        [1.1818],
        [1.4930]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5344510674476624


tensor([[1.6203],
        [1.3459],
        [0.9576],
        [1.3189],
        [1.7887]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5834032297134399


tensor([[1.3819],
        [1.0701],
        [1.6310],
        [1.3099],
        [1.5001]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5276123881340027


tensor([[1.3944],
        [1.5012],
        [1.5021],
        [1.1894],
        [1.3396]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4923557937145233


tensor([[1.3637],
        [1.4493],
        [1.0159],
        [1.1177],
        [1.3776]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5266032218933105


tensor([[1.8031],
        [1.6412],
        [1.0890],
        [1.5885],
        [1.4531]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4937545955181122


tensor([[1.6665],
        [1.7788],
        [1.3748],
        [1.3205],
        [1.1523]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4435916543006897


tensor([[1.2997],
        [1.3299],
        [1.5289],
        [1.4442],
        [1.2855]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4826825261116028


tensor([[1.1959],
        [1.1157],
        [1.5441],
        [1.6342],
        [0.9895]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.44500428438186646


tensor([[1.4118],
        [1.7104],
        [1.6787],
        [1.2498],
        [1.6625]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.528714120388031


tensor([[1.3047],
        [1.5156],
        [1.7142],
        [1.3446],
        [1.6949]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5398630499839783


tensor([[1.0791],
        [1.3809],
        [1.3901],
        [1.7065],
        [1.1400]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.46469244360923767


tensor([[1.3129],
        [1.2366],
        [1.4668],
        [1.4486],
        [1.5513]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5310653448104858


tensor([[1.0265],
        [1.5705],
        [1.5141],
        [1.4178],
        [1.3084]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49169906973838806


tensor([[1.4921],
        [1.4320],
        [1.0076],
        [1.4585],
        [0.9089]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4369746148586273


tensor([[1.5502],
        [1.2624],
        [1.5043],
        [1.5194],
        [1.1570]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.454104483127594


tensor([[1.7880],
        [1.3929],
        [1.2787],
        [0.9469],
        [1.5805]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.543531596660614


tensor([[1.2316],
        [1.4450],
        [0.7897],
        [1.4520],
        [1.2495]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5107733607292175


tensor([[0.9833],
        [1.1754],
        [1.5481],
        [0.7468],
        [1.3571]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5507444739341736


tensor([[1.4016],
        [1.7430],
        [1.8907],
        [1.6378],
        [1.7448]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5210803747177124


tensor([[1.5119],
        [1.5257],
        [1.7205],
        [1.0343],
        [1.7188]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.549699604511261


tensor([[1.3295],
        [1.9085],
        [1.6631],
        [1.8477],
        [1.3848]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.46024689078330994


tensor([[1.6873],
        [1.3428],
        [1.3712],
        [1.4459],
        [1.4474]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4996017515659332


tensor([[1.5789],
        [1.3947],
        [1.7049],
        [1.3717],
        [1.6579]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5268675088882446


tensor([[1.1697],
        [1.5302],
        [1.4878],
        [1.5231],
        [1.3117]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48349905014038086


tensor([[1.1427],
        [1.4650],
        [1.4478],
        [1.4902],
        [1.1098]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4587533473968506


tensor([[1.2240],
        [1.1423],
        [1.4475],
        [1.2815],
        [1.5287]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5431737899780273


tensor([[1.4645],
        [1.3689],
        [1.2167],
        [1.6651],
        [1.3546]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49029284715652466


tensor([[1.0464],
        [1.1345],
        [1.5040],
        [1.0543],
        [1.1377]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49903783202171326


tensor([[0.9196],
        [1.4887],
        [1.4526],
        [1.3300],
        [1.4542]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5296127796173096


tensor([[1.0945],
        [1.4075],
        [1.2176],
        [1.4719],
        [1.0854]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4699741303920746


tensor([[1.7249],
        [1.4860],
        [1.2520],
        [1.2640],
        [1.2638]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47619539499282837


tensor([[1.2772],
        [1.4754],
        [1.4902],
        [1.7359],
        [1.5628]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5141005516052246


tensor([[1.3691],
        [1.9291],
        [1.6370],
        [1.4591],
        [1.5878]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5045543313026428


tensor([[1.6799],
        [1.0344],
        [1.4945],
        [1.3201],
        [1.3092]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4924885332584381


tensor([[1.3442],
        [1.7292],
        [1.5744],
        [1.5345],
        [1.4105]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4814789295196533


tensor([[0.8668],
        [1.2757],
        [1.3466],
        [1.5362],
        [1.2110]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4990009367465973


tensor([[1.1262],
        [1.0496],
        [1.5673],
        [1.3388],
        [1.1581]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4869094491004944


tensor([[1.6862],
        [1.4817],
        [1.0722],
        [1.2218],
        [1.2973]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4932425022125244


tensor([[1.5234],
        [1.6156],
        [1.1544],
        [1.1995],
        [1.7142]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5591486096382141


tensor([[1.3318],
        [1.4666],
        [1.1709],
        [1.1885],
        [1.5955]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5516120791435242


tensor([[1.4124],
        [1.5344],
        [1.6193],
        [1.7026],
        [1.4409]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4829346239566803


tensor([[1.7049],
        [1.5350],
        [1.1936],
        [1.3139],
        [1.3353]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.486764520406723


tensor([[1.5847],
        [1.8082],
        [1.7647],
        [1.5717],
        [1.4864]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4750850796699524


tensor([[1.3996],
        [1.2631],
        [1.3993],
        [1.3594],
        [1.2537]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48469313979148865


tensor([[1.4407],
        [1.6757],
        [1.3543],
        [1.3169],
        [1.3719]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4898035228252411


tensor([[1.2231],
        [2.1676],
        [1.6998],
        [1.7076],
        [1.3890]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4624722898006439


tensor([[0.7407],
        [1.3497],
        [1.4196],
        [1.3370],
        [1.3647]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5324873328208923


tensor([[1.3913],
        [1.5209],
        [1.1449],
        [1.5731],
        [1.3516]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49326059222221375


tensor([[0.9040],
        [0.9768],
        [0.9938],
        [1.3407],
        [1.2694]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5447896122932434


tensor([[1.5185],
        [1.3080],
        [1.5974],
        [1.5102],
        [1.0313]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.43150338530540466


tensor([[1.5495],
        [1.1938],
        [1.1577],
        [1.4087],
        [1.1529]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.475294828414917


tensor([[1.6310],
        [1.2621],
        [1.0994],
        [1.1049],
        [1.4105]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5260917544364929


tensor([[1.2716],
        [1.4411],
        [1.2288],
        [1.4993],
        [1.2261]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4802432954311371


tensor([[1.5162],
        [1.2381],
        [1.6997],
        [1.5019],
        [1.4443]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4956241548061371


tensor([[1.8101],
        [1.5610],
        [1.6416],
        [1.4887],
        [1.5146]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4871927797794342


tensor([[1.3158],
        [1.5066],
        [1.1511],
        [1.3473],
        [1.3677]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5076588988304138


tensor([[1.6324],
        [1.2151],
        [1.4900],
        [1.5141],
        [1.4751]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5043132901191711


tensor([[1.6288],
        [1.7752],
        [1.4837],
        [1.2358],
        [1.5564]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5085908770561218


tensor([[1.2365],
        [1.3170],
        [1.6582],
        [1.1057],
        [1.5074]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5320219993591309


tensor([[1.4286],
        [1.3216],
        [1.0000],
        [1.3028],
        [1.3244]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5130360722541809


tensor([[1.2832],
        [1.5833],
        [1.3499],
        [1.4098],
        [1.4589]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5096561908721924


tensor([[1.2009],
        [1.7792],
        [1.1075],
        [1.1434],
        [1.6160]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5556766390800476


tensor([[1.3198],
        [1.5938],
        [1.2174],
        [1.5564],
        [1.1314]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.45666590332984924


tensor([[1.2134],
        [1.2402],
        [1.2365],
        [1.2757],
        [1.2456]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5028066635131836


tensor([[1.6586],
        [1.0982],
        [1.1425],
        [1.7004],
        [1.3757]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5015417337417603


tensor([[1.5275],
        [1.4140],
        [1.3904],
        [1.4998],
        [1.2622]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4698514938354492


tensor([[1.6354],
        [1.4913],
        [1.2943],
        [1.6620],
        [1.3896]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48182669281959534


tensor([[1.1284],
        [1.2432],
        [1.4802],
        [1.5589],
        [1.3863]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.507835865020752


tensor([[1.2646],
        [1.6318],
        [1.0981],
        [1.5222],
        [1.5820]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5363014936447144


tensor([[1.2109],
        [1.6206],
        [1.6270],
        [1.0709],
        [1.2812]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48832473158836365


tensor([[1.4057],
        [1.0637],
        [1.7713],
        [1.3905],
        [1.4777]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5156924724578857


tensor([[1.5391],
        [1.5294],
        [1.2899],
        [1.4227],
        [0.9382]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4236225187778473


tensor([[1.4511],
        [1.2981],
        [1.4552],
        [1.5112],
        [1.7291]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5507016181945801


tensor([[1.3432],
        [1.3824],
        [1.2260],
        [1.6422],
        [1.3570]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49523496627807617


tensor([[1.4036],
        [1.3605],
        [1.2004],
        [1.0838],
        [1.6241]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5613310933113098


tensor([[1.2578],
        [1.0144],
        [1.4076],
        [1.0436],
        [1.3361]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.529938280582428


tensor([[1.2084],
        [1.7964],
        [1.1378],
        [1.4062],
        [1.1451]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.46668848395347595


tensor([[1.3488],
        [1.4439],
        [1.2050],
        [1.7863],
        [1.3628]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4900777339935303


tensor([[1.6761],
        [1.9319],
        [1.7290],
        [1.6347],
        [1.5727]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48191580176353455


tensor([[1.4036],
        [1.2046],
        [1.5039],
        [1.2860],
        [1.4847]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5231090784072876


tensor([[1.9379],
        [1.3271],
        [1.3143],
        [1.7389],
        [1.4468]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4855620563030243


tensor([[1.3322],
        [1.3849],
        [1.2705],
        [1.3845],
        [1.2135]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4804390072822571


tensor([[1.5225],
        [1.1701],
        [1.0776],
        [1.4820],
        [1.3519]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5094725489616394


tensor([[1.3763],
        [1.3040],
        [1.3790],
        [1.5757],
        [1.2643]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47820255160331726


tensor([[0.8928],
        [1.2036],
        [1.3565],
        [1.5256],
        [1.5665]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5575612187385559


tensor([[1.2095],
        [1.1667],
        [1.4070],
        [1.2099],
        [1.5749]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5550567507743835


tensor([[1.7434],
        [1.2604],
        [1.5850],
        [1.3328],
        [1.2286]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.46333155035972595


tensor([[1.5403],
        [1.5088],
        [1.6379],
        [1.8988],
        [1.6898]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5140610933303833


tensor([[1.1303],
        [1.8094],
        [1.4595],
        [1.4980],
        [1.2174]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.46377602219581604


tensor([[1.2873],
        [1.4278],
        [1.2589],
        [1.5677],
        [1.3475]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4953148365020752


tensor([[1.5112],
        [1.1289],
        [1.5117],
        [1.4196],
        [1.6153]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5384079813957214


tensor([[1.6568],
        [1.7438],
        [1.2416],
        [1.3092],
        [1.5770]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5186691284179688


tensor([[1.1926],
        [1.3508],
        [1.3612],
        [1.6536],
        [1.3513]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4960326850414276


tensor([[0.8595],
        [1.0824],
        [1.0965],
        [1.4415],
        [1.3023]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.537636935710907


tensor([[1.1130],
        [0.8429],
        [1.1328],
        [1.1470],
        [1.2947]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5467929840087891


tensor([[1.2762],
        [1.3009],
        [1.5098],
        [1.7212],
        [0.8436]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4105028212070465


tensor([[2.0052],
        [1.1356],
        [1.8425],
        [1.7443],
        [1.4294]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4714239537715912


tensor([[1.4873],
        [1.8365],
        [1.5204],
        [1.0708],
        [1.6353]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5314908027648926


tensor([[1.6625],
        [1.6721],
        [1.8339],
        [1.5784],
        [1.0265]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4028692841529846


tensor([[1.3849],
        [1.4667],
        [1.8641],
        [1.6439],
        [1.5267]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.495013564825058


tensor([[1.6655],
        [1.6560],
        [1.5905],
        [1.7211],
        [1.4855]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47751280665397644


tensor([[1.7757],
        [1.7293],
        [1.7996],
        [1.6958],
        [1.8148]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5213899612426758


tensor([[1.1003],
        [1.4094],
        [1.2374],
        [1.2428],
        [1.3950]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5261003375053406


tensor([[1.1979],
        [1.0472],
        [1.5067],
        [0.9686],
        [1.3075]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5266939997673035


tensor([[1.0643],
        [1.4664],
        [0.9113],
        [1.1221],
        [0.9770]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48404571413993835


tensor([[1.1991],
        [1.0733],
        [1.3135],
        [1.1569],
        [0.9351]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.46706971526145935


tensor([[1.4579],
        [1.4030],
        [1.1251],
        [1.6648],
        [1.5560]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5261805057525635


tensor([[1.3573],
        [1.1025],
        [1.6109],
        [1.5520],
        [1.1143]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.45760074257850647


tensor([[1.4090],
        [1.4170],
        [1.4484],
        [1.5602],
        [1.5012]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5079591274261475


tensor([[1.3443],
        [1.7381],
        [1.1581],
        [1.5899],
        [1.3825]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4917663633823395


tensor([[1.4780],
        [1.5275],
        [1.7138],
        [1.7710],
        [1.6032]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5022540092468262


tensor([[2.0450],
        [1.5586],
        [1.5220],
        [1.4645],
        [1.4093]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.46920067071914673


tensor([[1.3867],
        [1.3426],
        [1.0964],
        [1.4846],
        [1.2270]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4863336682319641


tensor([[1.3872],
        [1.1355],
        [1.9217],
        [1.4167],
        [1.3661]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4897196888923645


tensor([[1.3453],
        [1.5488],
        [1.6117],
        [1.4363],
        [1.5147]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5065752863883972


tensor([[1.5516],
        [1.7707],
        [1.3313],
        [1.1000],
        [1.0330]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4417278468608856


tensor([[1.2302],
        [1.1807],
        [1.2734],
        [1.6000],
        [1.7351]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5704795718193054


tensor([[1.6552],
        [1.1925],
        [0.9889],
        [1.2539],
        [1.1702]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.489536851644516


tensor([[1.1153],
        [1.3131],
        [1.1544],
        [1.2967],
        [1.0233]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47356587648391724


tensor([[1.2172],
        [1.0674],
        [1.4385],
        [1.3255],
        [1.0017]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4635758399963379


tensor([[1.4881],
        [1.5437],
        [1.2129],
        [1.6611],
        [1.8760]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5699859857559204


tensor([[1.5623],
        [1.2168],
        [1.5897],
        [1.4783],
        [1.3590]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4856925904750824


tensor([[1.7704],
        [1.6781],
        [1.2696],
        [1.3641],
        [1.6534]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5264391303062439


tensor([[1.0031],
        [1.1853],
        [1.1846],
        [1.6770],
        [1.1992]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49600574374198914


tensor([[1.5468],
        [1.5510],
        [1.4133],
        [1.0814],
        [1.4544]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5118856430053711


tensor([[1.4127],
        [1.4628],
        [1.3465],
        [1.6887],
        [1.7968]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5554511547088623


tensor([[1.6314],
        [1.4399],
        [1.8443],
        [1.6015],
        [1.4221]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4719943106174469


tensor([[1.6663],
        [1.6649],
        [1.3182],
        [1.2495],
        [1.3180]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47813764214515686


tensor([[1.5142],
        [1.4095],
        [1.1122],
        [1.8013],
        [1.5940]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5266816020011902


tensor([[1.3647],
        [1.3948],
        [1.1791],
        [1.4885],
        [1.2494]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48441678285598755


tensor([[0.7827],
        [1.0765],
        [1.2963],
        [0.6990],
        [1.4107]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5888190269470215


tensor([[1.4476],
        [1.0989],
        [1.1275],
        [1.6967],
        [1.4835]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5271100401878357


tensor([[1.4556],
        [1.4776],
        [1.2280],
        [1.1453],
        [1.9199]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.6010084748268127


tensor([[1.2867],
        [1.2093],
        [1.5078],
        [1.3252],
        [1.5596]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5382117629051208


tensor([[1.3873],
        [1.0316],
        [1.3378],
        [1.2508],
        [1.5566]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5521039366722107


tensor([[1.6139],
        [1.4179],
        [1.3811],
        [1.5162],
        [1.4929]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5033451318740845


tensor([[1.4988],
        [1.7286],
        [1.4798],
        [1.3617],
        [1.3643]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4780271053314209


tensor([[1.3045],
        [1.3954],
        [1.6557],
        [1.3004],
        [1.4165]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.502147912979126


tensor([[1.2529],
        [1.2223],
        [1.3361],
        [1.8313],
        [1.4980]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5182470679283142


tensor([[1.6496],
        [1.3979],
        [1.2034],
        [1.7856],
        [1.7963]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5527930855751038


tensor([[1.1770],
        [1.0137],
        [1.3399],
        [1.8747],
        [1.1626]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4776465594768524


tensor([[1.2055],
        [1.4754],
        [1.3516],
        [1.3981],
        [1.2425]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4830106198787689


tensor([[1.4759],
        [1.2216],
        [1.5597],
        [1.2601],
        [0.8515]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.42231032252311707


tensor([[1.3582],
        [1.4498],
        [1.5885],
        [1.5700],
        [1.4018]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.487253874540329


tensor([[1.6724],
        [1.3749],
        [1.2422],
        [1.4438],
        [1.3252]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4847869575023651


tensor([[1.5533],
        [1.0933],
        [1.3446],
        [1.3653],
        [1.0701]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4609803259372711


tensor([[1.3198],
        [1.3041],
        [1.4748],
        [1.3051],
        [1.2308]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.48199358582496643


tensor([[1.6369],
        [1.3452],
        [1.2842],
        [1.1586],
        [1.8229]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5798819065093994


tensor([[1.5251],
        [1.2727],
        [1.4460],
        [1.3441],
        [1.4582]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5108752250671387


tensor([[1.8438],
        [1.8916],
        [1.4982],
        [1.8594],
        [1.5569]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4764050543308258


tensor([[1.4813],
        [1.4376],
        [1.2741],
        [1.4399],
        [1.4817]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5127358436584473


tensor([[1.4845],
        [1.1558],
        [1.0604],
        [1.1578],
        [1.3763]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.52999347448349


tensor([[1.2629],
        [1.2569],
        [1.4657],
        [1.5246],
        [1.2234]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47709718346595764


tensor([[1.1845],
        [1.6728],
        [1.1675],
        [1.4735],
        [1.5939]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5389881134033203


tensor([[1.3708],
        [1.3664],
        [1.3625],
        [1.3391],
        [1.6846]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.553788959980011


tensor([[1.1059],
        [1.2226],
        [1.0412],
        [1.4068],
        [1.5398]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5598880648612976


tensor([[1.2788],
        [1.3792],
        [0.8872],
        [1.4296],
        [1.3249]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5180556178092957


tensor([[1.5463],
        [1.1766],
        [1.5647],
        [1.5552],
        [1.2896]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4752424657344818


tensor([[1.5741],
        [1.5716],
        [1.8867],
        [1.5482],
        [1.2151]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.43716880679130554


tensor([[1.7872],
        [1.5753],
        [1.7007],
        [1.3899],
        [1.7574]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5299009084701538


tensor([[1.2537],
        [1.4841],
        [1.4978],
        [1.5179],
        [1.5993]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5277414917945862


tensor([[1.2705],
        [1.4345],
        [1.4588],
        [1.1770],
        [1.3949]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5110182166099548


tensor([[1.5283],
        [1.2556],
        [1.3906],
        [1.4361],
        [1.1657]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4639376103878021


tensor([[1.3387],
        [1.5914],
        [1.7327],
        [1.0715],
        [1.3729]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.49485453963279724


tensor([[1.0766],
        [1.5010],
        [1.3766],
        [1.2010],
        [1.1305]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.4785802960395813


tensor([[1.3106],
        [1.1552],
        [1.1379],
        [1.2731],
        [1.0521]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.47781306505203247


tensor([[1.1489],
        [1.4846],
        [1.5582],
        [1.4071],
        [1.4229]], device='cuda:0', grad_fn=<ThAddmmBackward>)
0.5056911110877991


KeyboardInterrupt: 

In [ ]:
losses

In [ ]:
avg_losses = [average_data(epoch_losses) for epoch_losses in losses]
avg_predictions = [average_data(epoch_evaluations) for epoch_evaluations in evaluations]

In [ ]:
min_loss, max_loss, avg_loss = get_statistics(avg_losses, "loss")
print(min_loss)

In [ ]:
min_auc, max_auc, avg_auc = get_statistics(avg_predictions, "auc")

In [ ]:
print(max_auc)

In [ ]:
print(min_auc)