Linear weight analysis from a linear model trained on the large weakly labeled dataset, where the attention has been extracted from a BERT model not pretrained on bias detection.

In [3]:
import torch

In [4]:
model = torch.load("../../../workshop_experiments/attention_no-pretrain/large_data/concat_all/model_weights/linear-windowed-attention.weights")

In [3]:
model

OrderedDict([('f1.weight',
              tensor([[ 0.2441,  0.3389,  0.1353,  ...,  0.0888, -0.0596, -0.1424],
                      [ 0.0161,  0.0614, -0.0104,  ..., -0.0753,  0.0011,  0.1191],
                      [ 0.0808,  0.0628,  0.0843,  ...,  0.0313,  0.0014, -0.0647],
                      ...,
                      [ 0.1449, -0.0630, -0.0546,  ...,  0.0456, -0.0499,  0.0582],
                      [ 0.0818,  0.1267,  0.1249,  ..., -0.0564, -0.0419, -0.0077],
                      [ 0.0826,  0.0639,  0.0646,  ...,  0.0353,  0.0146, -0.0041]],
                     device='cuda:0')),
             ('f1.bias',
              tensor([ 0.1247,  0.0546,  0.0995,  0.0320,  0.0184,  0.1033,  0.1833,  0.1352,
                       0.0473, -0.0389,  0.1775,  0.0536,  0.2242,  0.1189,  0.1500],
                     device='cuda:0')),
             ('f2.weight',
              tensor([[-1.7709, -1.6677,  1.0377, -1.4134, -1.3327, -2.2204, -1.8000,  1.2801,
                       -1.6625,  0

In [4]:
model['f1.weight'].shape

torch.Size([15, 180])

In [5]:
# Analysis of the first layer (15 )
torch.sum(model['f1.weight'][:,:15],dim=0) # Framing is 1 epistemological is 0 

tensor([ 1.1982,  1.2352,  1.1688,  1.2211,  0.9052,  1.0749,  3.9061, -0.4757,
        -8.9996,  0.2985,  1.1857, -0.8404,  0.2110, -0.3476, -0.6776],
       device='cuda:0')

In [6]:
running_sum = torch.zeros(15, dtype=torch.float)
for i in range(12):
    start_idx = i * 15
    end_idx = (i+1) * 15
    running_sum = running_sum + torch.sum(model['f1.weight'][:,start_idx:end_idx],dim=0).cpu()
print(running_sum/12)

tensor([ 0.2552,  0.3184,  0.3716,  0.2921,  0.3098, -0.1689, -0.4891, -1.8051,
        -0.6030, -1.0823, -0.0882, -0.3554, -0.0412, -0.0746,  0.1774])


In [7]:
for i in running_sum/12:
    print(i.item())

0.25521594285964966
0.31844648718833923
0.3715747594833374
0.29207345843315125
0.309754341840744
-0.16885323822498322
-0.48910796642303467
-1.8051198720932007
-0.6029573082923889
-1.0822745561599731
-0.08822081238031387
-0.3553757667541504
-0.041196953505277634
-0.07459313422441483
0.17738713324069977
