Linear weight analysis from a linear model trained on the large weakly labeled dataset, where the attention has been extracted from the pretrained BERT model.

In [1]:
import torch

In [2]:
model = torch.load("../../../workshop_experiments/attention_pretrained/large_data/concat_all/model_weights/linear-windowed-attention.weights")

In [3]:
model

OrderedDict([('f1.weight',
              tensor([[-0.1803,  0.0370,  0.1251,  ...,  0.0485, -0.0409,  0.2689],
                      [-0.0442, -0.0580, -0.0526,  ..., -0.1368, -0.0231, -0.0193],
                      [-0.0577, -0.0292, -0.0330,  ...,  0.0874,  0.1158, -0.0968],
                      ...,
                      [-0.0890,  0.0353,  0.0518,  ..., -0.0246, -0.0109,  0.2641],
                      [ 0.0921,  0.1613,  0.2801,  ..., -0.0031,  0.1427, -0.0581],
                      [ 0.3360,  0.1887,  0.0465,  ...,  0.1261,  0.1885, -0.1304]],
                     device='cuda:0')),
             ('f1.bias',
              tensor([ 0.0163, -0.0994, -0.0268,  0.3977, -0.0270, -0.0399, -0.0545,  0.0394,
                      -0.1553, -0.0222,  0.2626,  0.3423,  0.0026, -0.1142,  0.3070],
                     device='cuda:0')),
             ('f2.weight',
              tensor([[ 0.6584, -0.1798,  1.3266, -0.6571,  0.0736,  1.4193,  1.4660,  3.5430,
                        2.7260,  1

In [4]:
model['f1.weight'].shape

torch.Size([15, 180])

In [5]:
# Analysis of the first layer (15 )
torch.sum(model['f1.weight'][:,:15],dim=0) # Framing is 1 epistemological is 0 

tensor([ 1.4897,  1.0427,  0.5426,  1.1156,  0.7356,  1.1256, -1.6700, -1.9723,
         6.2024, -0.5142, -1.3770,  1.1462, -1.0289, -0.6548, -1.0667],
       device='cuda:0')

In [6]:
running_sum = torch.zeros(15, dtype=torch.float)
for i in range(12):
    start_idx = i * 15
    end_idx = (i+1) * 15
    running_sum = running_sum + torch.sum(model['f1.weight'][:,start_idx:end_idx],dim=0).cpu()
print(running_sum/12)

tensor([ 0.5565,  0.5228,  0.4986,  0.5779,  0.3773,  0.5772, -0.2338,  0.1052,
        -0.2187, -0.4096,  0.2852,  0.1007,  0.0446,  0.2137, -0.1303])


In [7]:
for i in running_sum/12:
    print(i.item())

0.5565373301506042
0.5228064656257629
0.4986400604248047
0.5779280066490173
0.37726321816444397
0.5772495865821838
-0.2338053435087204
0.105185367166996
-0.21868400275707245
-0.40956056118011475
0.28524449467658997
0.10071172565221786
0.044627949595451355
0.21371996402740479
-0.13027894496917725
